In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [ ]:
dataset = pd.read_csv('Data2.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[[1 'france' 44.0 72000.0]
 [2 'spain' 27.0 48000.0]
 [3 'germany' 30.0 54000.0]
 [4 'spain' 38.0 61000.0]
 [5 'germany' 40.0 nan]
 [6 'france' 35.0 58000.0]
 [7 'spain' nan 52000.0]
 [8 'france' 48.0 79000.0]
 [9 'germany' 50.0 83000.0]
 [10 'france' 37.0 67000.0]
 [11 'indonesia' 34.0 54000.0]
 [12 'france' nan 78000.0]
 [13 'germany' 65.0 nan]
 [14 'brazil' 55.0 40000.0]
 [15 'belanda' 33.0 50000.0]]


In [ ]:
dataset = pd.read_csv('Data2.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[[1 'france' 44.0 72000.0]
 [2 'spain' 27.0 48000.0]
 [3 'germany' 30.0 54000.0]
 [4 'spain' 38.0 61000.0]
 [5 'germany' 40.0 nan]
 [6 'france' 35.0 58000.0]
 [7 'spain' nan 52000.0]
 [8 'france' 48.0 79000.0]
 [9 'germany' 50.0 83000.0]
 [10 'france' 37.0 67000.0]
 [11 'indonesia' 34.0 54000.0]
 [12 'france' nan 78000.0]
 [13 'germany' 65.0 nan]
 [14 'brazil' 55.0 40000.0]
 [15 'belanda' 33.0 50000.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)


In [ ]:
print(y)



[0 1 0 0 1 1 0 1 0 1 1 0 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)


In [ ]:
print(x_train)

[[0.0 0.0 0.0 1.0 0.0 0.0 30.0 54000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 34.0 54000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 40.0 61230.769230769234]
 [0.0 0.0 0.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 55.0 40000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 33.0 50000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 37.0 67000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 65.0 61230.769230769234]
 [0.0 0.0 1.0 0.0 0.0 0.0 41.23076923076923 78000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(x_test)

[[0.0 0.0 0.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 48.0 79000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 41.23076923076923 52000.0]]


In [ ]:
print(y_train)

[0 1 1 1 0 0 1 1 0 1 0 1]


In [ ]:
print(y_test)

[0 1 0]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.fit_transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 0.0 0.0 1.4142135623730951 -0.3015113445777637 -0.30151134457776363
  -1.0329594484020912 -0.5390463993494963]
 [0.0 0.0 0.0 -0.7071067811865475 3.3166247903554007 -0.30151134457776363
  -0.6551360628200836 -0.5390463993494963]
 [0.0 0.0 0.0 1.4142135623730951 -0.3015113445777637 -0.30151134457776363
  -0.08840098444707245 0.05707550110759395]
 [0.0 0.0 0.0 -0.7071067811865475 -0.3015113445777637 3.3166247903554
  -1.3163269875885968 -1.0337007422819753]
 [0.0 1.0 0.0 -0.7071067811865475 -0.3015113445777637
  -0.30151134457776363 1.3284367114854556 -1.693239866191947]
 [0.0 0.0 1.0 -0.7071067811865475 -0.3015113445777637
  -0.30151134457776363 0.289422401134935 0.9449166294479404]
 [1.0 0.0 0.0 -0.7071067811865475 -0.3015113445777637
  -0.30151134457776363 -0.7495919092155855 -0.8688159613044822]
 [0.0 0.0 1.0 -0.7071067811865475 -0.3015113445777637
  -0.30151134457776363 -0.37176852363357804 0.532704677004208]
 [0.0 0.0 0.0 1.4142135623730951 -0.3015113445777637 -0.3015113445777